/**
 * Lo que el bot de WhatsApp de PeluDesk puede afirmar (28 de septiembre de 2026).
 *
 * Regla: aquí solo entra lo que la app HACE HOY, con las palabras de la
 * landing. Los planes y precios NO van aquí: salen de la base en cada
 * conversación (tabla `planes`, que edita la plataforma). Si una función
 * cambia en la app, se cambia aquí también; si no está aquí, el bot no lo
 * sabe y lo pasa a Telegram. Lo que el operador enseña desde Telegram
 * (/aprender) se suma en `wa_aprendido` sin desplegar.
 */
export const CONOCIMIENTO = `
# Qué es PeluDesk
Software para guarderías, hoteles y estéticas caninas, hecho en México. Se usa desde el navegador: en la computadora del mostrador, en una tableta o en el celular de cualquiera del equipo. No hay que instalar nada.
PeluDesk es una marca de Menteo, S.A.S.
Cada negocio tiene su propia dirección: <su-nombre>.peludesk.mx.

# Qué le quita de encima al negocio
- En la mañana: abres y ya ves quién llega, quién se va, las citas de estética y el cupo de día y de noche. También lo que está esperando (contratos por firmar, cartillas por revisar, saldos), con los días que lleva cada uno.
- Vacunas: si una vacuna venció, no deja reservarle guardería ni hotel al perro, y dice cuál falta. En estética no bloquea.
- Precios de estética: tres baños (completo, rapado y exprés) con precio por grupo de raza o, para mestizos y perros sin raza de catálogo, por tamaño y pelaje (chico/mediano/grande × corto/medio/largo); precio aparte si el perro llega con el pelo maltratado; el rapado solo para pelo medio o largo; un recargo manual con motivo lo registra quien tiene el permiso de excepciones, y el dueño ve la nota «el costo puede aumentar según el tipo de pelo y el cuidado previo». El alta de un cliente de solo estética es corta (nombre y WhatsApp del dueño; nombre, raza, tamaño y pelaje del perro). Al cliente que se dio de alta en el mostrador se le puede mandar un enlace de un solo uso (Invitar al portal, en su ficha) para que abra su cuenta. Si la raza no está en el catálogo, quien captura al perro la propone ahí mismo («No la encuentro: agregar esta raza», con nombre, otros nombres, talla, pelo y notas); la revisa PeluDesk y el negocio decide el grupo de precio de la raza: nunca se adivina, y sin grupo no se agenda la estética de ese perro. Al agendar, la pantalla calcula el precio y, si falta el tamaño o el pelaje del perro, los pide ahí mismo; si una combinación no tiene precio (matriz vacía en un negocio nuevo, o rizado), da UN aviso con dos salidas: agregar el precio en Servicios y precios, o registrar una excepción con motivo (con el permiso de excepciones). Un negocio nuevo llena su matriz de mestizos en Servicios y precios; a algunos negocios se les calculó el pelo medio y largo por proporción y salen marcados «Calculado» hasta que el admin los confirma o edita.
- Cupo: guardería y hotel cuentan del mismo cupo; no se acepta un perro que no cabe.
- Expediente de cada perro: foto, vacunas, alertas de manejo (si se escapa, si es alérgico, si come aparte), medicamentos y bitácora del día con fotos.
- Reporte de comportamiento diario (guardería): por cada perro que está adentro, recepción llena en la tablet o el celular un formulario con botones grandes (estado general, actividades, socialización, conducta, alimentación, descanso, recomendaciones y resumen del día) y la app arma una tarjeta con la marca del negocio. Se manda por WhatsApp como una liga, no como archivo, y vence a los 7 días. Las opciones las edita el admin (renombrar, apagar o agregar). No se genera ni se envía nada en bloque: cada reporte lo revisa una persona.
- Fotos y videos de los perros adentro (guardería y hotel): en «Adentro ahora» cada perro trae «Tomar foto», «Tomar video» y «Elegir de la galería»; el personal escoge lo que quiere y se lo manda al dueño por WhatsApp como liga a una galería. Los videos pueden durar hasta 45 segundos y pesar hasta 60 MB. Todo se borra solo a los 7 días (el negocio puede cambiarlo) y la liga deja de funcionar. Lo usan admin y las personas de recepción a quienes el admin les da el permiso «Reportes de guardería».
- Estética: agenda con una columna por estilista, sin citas encimadas. Al terminar la cita se descuenta del inventario lo que se usó. La estilista de una cita se cambia desde el tablero del día o desde la cita: antes de empezar o en curso lo hace recepción o admin en un toque (también «Sin asignar»); corregirla cuando el servicio ya terminó es de admin o de quien tenga el permiso «Corregir estilista de servicios cerrados», con motivo, y queda un historial en la cita. Si la nómina ya se pagó, el pago no cambia: la diferencia de comisión y propina se ajusta en el siguiente pago.
- Anular o corregir un cobro (sin usar descuentos): en la cuenta, «Anular cobro», «Corregir monto» (lo recibido en un método) o «Corregir precio» (una línea de la cuenta), siempre con motivo; nada se borra y queda quién, cuándo y el valor de antes. Un cobro anulado sale de turno, reportes, comisiones y conciliación y la cuenta vuelve a quedar por cobrar. Aplica a efectivo, transferencia y tarjeta (registro manual); un cobro con terminal o link de Mercado Pago o Clip no se anula: se devuelve con «Devolver con Mercado Pago». En un turno ya cerrado hace falta el permiso «Corregir cobros de turnos cerrados» y el corte cerrado no cambia (la corrección entra al turno abierto). Los permisos «Anular cobros» y «Editar monto de cobros» vienen apagados para recepción; el admin los da por persona.
- Agregar efectivo a la caja: en Caja → Turno, «Agregar efectivo» (cambio, préstamo de otra caja, aportación del dueño u otro, con nota). No es venta ni ingreso; sí suma al efectivo esperado del arqueo (fondo + cobros en efectivo + efectivo agregado − retiros). Se cancela con motivo mientras el turno siga abierto. Permiso «Agregar efectivo a caja» (apagado para recepción).
- Estética, citas: «Reprogramar» (desde la agenda o la cita) cambia fecha y hora revisando que la estilista no tenga otra cita, deja historial y ofrece un botón de WhatsApp para avisar al cliente (la app no manda nada sola); una cita ya cobrada no se reprograma sin anular el cobro. «Cancelar cita» (el cliente avisó) y «No se presentó» son distintas; ninguna borra la cita y las dos piden motivo. «Eliminar cita» es solo para una cita por error o duplicada, con motivo y el permiso «Eliminar citas». Al agendar, «Agregar otro perrito de este cliente» crea o escoge otro perro del dueño con su propia cita y cuenta, y se pueden cobrar juntas.
- Tarifa «Cliente de guardería» en estética: una tarifa (no un descuento) con el precio del baño exprés para los perros que usan la guardería; el admin la enciende y la configura en Administración → Tarifa de guardería (viene apagada); quitarla en una cita pide motivo y el permiso de excepciones.
- Corregir el servicio de una cita de estética (cuando se capturó uno que no era): en el detalle de la cita, «Corregir servicio», en cualquier momento (abierta, en curso o ya terminada y cobrada). Es de admin o de quien tenga el permiso «Corregir servicio de citas» (viene apagado; el admin lo da por persona en Permisos), con motivo obligatorio. El precio se recalcula con las reglas de la cita (grupo de precio, talla, pelo, excepciones) y se ve la diferencia antes de confirmar. El cobro original nunca se toca ni se borra: si había un cobro en la terminal o un link de pago abierto por el monto anterior, se cancela antes (nunca uno que Mercado Pago ya aprobó); si ya estaba cobrada y cuesta más, la cuenta queda con un cobro adicional que se cobra en Caja; si cuesta menos, queda un saldo a favor que un admin devuelve (con Mercado Pago, «Devolver con Mercado Pago»). Mientras esté pendiente sale en «Necesita atención» y en Caja → Ajustes por corrección de servicio. Si el servicio ya estaba terminado también se ajusta el inventario y, si la comisión ya se pagó, la diferencia sale como ajuste en el siguiente pago de nómina. Queda un historial inmutable en la cita (servicio y precio de antes y de ahora, quién, cuándo y motivo). Una cita vieja cuyo servicio se retiró del catálogo sigue mostrando el servicio con el que se registró y se corrige igual.
- Cobros con terminal: solo cuentan como cobrados cuando Mercado Pago confirma un pago aprobado (la app lo consulta directo: mismo monto, cuenta y referencia); si algo no cuadra la orden queda «Por confirmar con Mercado Pago» (no es dinero) y se resuelve con «Revisar con Mercado Pago». Con Mercado Pago o Clip elegidos, «Terminal» no se captura a mano: si la terminal no se puede usar (caída, sin señal, otra terminal) se registra el cobro con «Tarjeta (registro manual)», con el folio del voucher y el motivo; cuenta como pagado desde que se registra pero queda «Sin verificar» y aparece como línea aparte («Tarjeta manual (sin verificar)») en el turno, el corte y los reportes, nunca mezclado con la terminal verificada. El admin lo revisa en Caja → Conciliación («Revisado con voucher» o «Marcar como no recibida», con motivo y sin borrar nada); hay un tope de alerta por cobro (por omisión $2,000, lo cambia el admin en Cobro con terminal) y un aviso si se usa de más con la terminal conectada. Es un permiso, «Registrar tarjeta manual», que viene prendido para la recepción. Cada hora la app concilia los cobros con terminal contra los pagos de Mercado Pago que se cobraron desde PeluDesk (orden o link de PeluDesk, o la terminal vinculada) y marca las diferencias en «Necesita atención» (no corrige solo); los demás pagos de la cuenta de Mercado Pago (otra tienda, transferencias, otras terminales, cobros personales) se ignoran, y el admin puede ver esos otros pagos solo como información con la opción «Mostrar también otros pagos de mi cuenta» en Cobro con terminal; el admin corrige un cobro a mano que no se recibió con «Marcar como no recibido» (se comprueba con Mercado Pago, con motivo e historial).
- Cobrar varios servicios juntos: si una persona tiene varias cuentas abiertas (por ejemplo baño y guardería), en Caja salen agrupadas con su total junto y el botón «Cobrar todo junto» (también se pueden marcar casillas de las cuentas de la misma persona; nunca se mezclan personas). Se cobra en un solo movimiento: un solo pago, una sola propina, un solo folio de voucher y un recibo con el desglose por cuenta; el monto se reparte entre las cuentas (la más antigua primero, con montos editables por cuenta) y lo que falte queda como saldo de cada una. Con la terminal o un link se manda una sola orden por el total y, cuando el proveedor confirma, se reparte entre las cuentas. En el turno y el corte cuenta una sola vez. Revisar la tarjeta manual, marcarla como no recibida o «Marcar como no recibido» aplican a todo el grupo. Las devoluciones y reembolsos, las correcciones de servicio o de estilista, el inventario, las comisiones y la nómina siguen por cuenta. Una cuenta nunca queda debiendo menos de un peso: los descuentos por porcentaje dejan el total en pesos enteros.
- Caja: noches, guardería, baño y extras en una sola cuenta. Se cobra en efectivo, transferencia o tarjeta, se da cambio y en la noche se cuadra la caja (turno, retiros y arqueo).
- Cobro con terminal: cada negocio conecta SU cuenta de Mercado Pago (terminal Point Smart y links de pago) o su terminal Clip, desde Administración → Cobro con terminal. Al desconectar Mercado Pago se cancelan las órdenes en cola y la app recuerda la terminal; al reconectar la misma cuenta la recupera, y si no, el admin la escoge en Administración → Cobro con terminal (mientras, «Cobrar con terminal» sale deshabilitado). Si la terminal pide cobros vinculados o no recibe el cobro: en la terminal, Más opciones → Ajustes → Modo de vinculación, para volver a modo independiente. El cobro a mano funciona siempre. La comisión de la terminal se registra sola como gasto cuando el proveedor la informa.
- Devoluciones: un cobro que entró por Mercado Pago (terminal o link) se devuelve desde la app, total o parcial; Mercado Pago lo reembolsa y queda en la caja en el mismo paso, y la comisión que regresa se quita de los gastos. Lo que se reembolse desde el panel de Mercado Pago también entra solo a la caja y sale en «Necesita atención». Con Clip, la devolución se hace en Clip y en la app se registra.
- Venta rápida en Caja: vender un producto del inventario (shampoo, croquetas, un collar) o cualquier concepto con su monto, sin reserva ni perro; con cliente o a «Público en general». Descuenta el inventario y sale aparte en el corte y los reportes.
- Ayuda dentro de la app: artículos paso a paso de cada pantalla (también en https://peludesk.mx/ayuda), un asistente que contesta con esos artículos y tickets de soporte con respuesta de una persona de PeluDesk.
- Day pass y mensualidades de guardería, por perro. Si un pase ya traía días usados de antes de registrarlo, o un check-in descontó un día de más, de menos o por error, quien tenga el permiso «Ajustar días de pases» (los admin siempre; a recepción se lo da un admin por persona en Permisos, viene apagado) lo corrige con «Ajustar días usados» en el pase, con un motivo obligatorio y viendo el antes y el después (días usados, restantes y vencimiento). Al vender un pase hay una casilla «Este paquete ya lleva días usados». Un check-in hecho por error de un perro con pase se deshace con «Deshacer este check-in»: el perro vuelve a «reservada» y el día regresa al pase. Un ajuste solo cambia el saldo de días: no cobra nada, no mueve la caja ni los reportes de dinero, y queda en el historial del pase (no se edita ni se borra: se corrige con otro ajuste). Si el pase ya venció, solo un admin puede extender su vigencia. El dueño ve en su portal el saldo ya corregido, nunca el historial interno.
- Recolección a domicilio con cargo por kilómetro.
- Contratos: plantillas propias; el dueño del perro firma con el dedo desde su celular; también se pueden subir contratos en papel. Son de guardería y hotel: en estética no hay contratos (a una estética no le ofrezcas contratos).
- Portal de clientes: el dueño del perro entra desde el navegador de su celular con su teléfono y su contraseña. Ve sus citas, vacunas, fotos del día, pases y contratos, y firma. Nunca ve los precios internos ni a otros clientes.
- Alta de clientes por link: recepción manda un link por WhatsApp y el dueño captura sus datos y los de sus perros desde su casa. Con guardería u hotel prendidos, el link también le pide la foto o el PDF del carnet de vacunas; lo que sube lo revisa recepción antes de contar, y si no lo sube el perro queda «sin registro» y no puede reservar guardería ni hotel.
- Inventario: consumibles con mínimo de existencia y compras; equipo (secadoras, jaulas) con su mantenimiento.
- Empleados: asistencia, retardos, ausencias y vacaciones, comisiones de estética, propinas, adelantos y nómina.
- Gastos del local, con gastos recurrentes y comprobantes.
- Reportes: ingresos, costos, margen por servicio y utilidad (lo cobrado menos insumos, nómina y gastos del local), comparado con el periodo anterior.
- Página web del negocio con sus servicios, precios, fotos, horario y WhatsApp.
- Permisos: el admin le puede dar a una persona de recepción permisos extra (costos e inventario, tarifas, reportes, personal, configuración, gastos, nómina, entre otros) en Administración → Permisos.
- Roles: admin (dueño), recepción, estética y cliente (dueño del perro).
- Módulos: el admin prende y apaga los módulos de su plan en Administración → Módulos y plan. Apagar un módulo nunca borra nada.

# Prueba gratis
- 15 días gratis, sin tarjeta. Se registra en https://peludesk.mx/registro con su teléfono, una contraseña, el nombre del negocio, su ciudad y los servicios que ofrece (guardería, hotel, estética, veterinaria).
- Durante la prueba están disponibles los módulos del plan Completo, más la página web. Los servicios que NO escogió al registrarse (guardería, hotel o estética) arrancan apagados; los prende cuando quiera en Administración → Módulos y plan.
- Al entrar hay cinco primeros pasos para dejarlo listo.
- Página web gratis de por vida si en los primeros 7 días de la prueba completa su perfil: primeros pasos, logo (PNG, JPG, WebP o SVG de hasta 2 MB; antes de guardar ve cómo se verá en su registro, recibos y portal, y la app avisa si es muy ancho o trae fondo blanco), 3 fotos, al menos un precio, horario y dirección. Si no, la página web es un complemento con costo.
- Cuando termina la prueba no se borra nada: puede consultar todo y vuelve a capturar en cuanto contrata.
- En la prueba, mientras no conecte su cuenta de Mercado Pago o Clip, la terminal y los links funcionan en simulación (no mueven dinero). Si ya conectó su cuenta real, los cobros son de verdad.

# Demo
Hay un negocio de ejemplo, Patitas & Co., con dos meses de movimiento inventado. Se puede entrar como recepción, estilista, dueña del negocio o dueña de un perro. Es de solo lectura: nada se guarda.

# Contratar y pagar PeluDesk
- Se paga por negocio, al mes o al año. No se cobra por perro ni por cliente.
- Los precios son más IVA (16 %). Si paga el año, paga diez meses.
- Se contrata desde la app: Administración → Módulos y plan. El pago es con tarjeta, por Stripe.
- Si contrata durante la prueba no pierde días: el primer cobro es cuando termina la prueba.
- Subir de plan (o pasar de mensual a anual) es inmediato, cobrando la diferencia proporcional. Bajar de plan toma efecto al terminar el periodo pagado, y antes avisa qué módulos se apagan.
- Cambiar la tarjeta, ver facturas de Stripe o cancelar: desde Administración → Módulos y plan, en el portal de pagos.
- Cancelar: cuando quiera; lo sigue usando hasta que termina lo que ya pagó.
- Si un cobro falla: todo sigue funcionando 7 días (gracia) mientras actualiza la tarjeta. Desde el día 8 la cuenta queda en solo lectura: nada se borra y todo se puede consultar. En cuanto se paga, se reactiva solo.
- Factura fiscal (CFDI): PeluDesk no la emite desde la app. Eso se escala.

# Dudas frecuentes de uso (dónde está cada cosa)
- Entrar: con su teléfono o correo y su contraseña, en la dirección de su negocio.
- Invitar a alguien de su equipo: Administración (sección de personal).
- Precios y servicios: Servicios.
- Horario del negocio y datos: Administración.
- Perfil y página web: Administración → Perfil y página web.
- Conectar la terminal: Administración → Cobro con terminal.
- Plan, módulos y pago: Administración → Módulos y plan.
- El tablero del día está en la pantalla de inicio de recepción.
- Clientes y sus perros: Clientes. Reservas de guardería y hotel: Guardería y Hotel. Citas: Estética. Cobros: Caja.
- La contraseña de un cliente la restablece el negocio desde la ficha del cliente.

# Veterinaria (módulo nuevo, Fase 0)
- Es un módulo aparte, junto a Hotel y guardería y Estética. Viene apagado: el admin lo prende en Administración → Módulos y plan (necesita Inventario prendido) y también puede escogerlo al registrarse en la prueba gratis. Apagarlo no borra nada.
- Hoy incluye: ficha clínica de la mascota (especie perro, gato u otro; esterilización; peso con historial por fecha; alergias; microchip; folio de registro como el RUAC; notas clínicas), inventario clínico con lotes y caducidades, médicos veterinarios con cédula, CPA del SITPV y folios, y los datos del establecimiento (aviso de funcionamiento ante SENASICA, MVRA y permisos con fecha de vencimiento y recordatorio).
- Cada producto clínico tiene dos clasificaciones independientes y editables: grupo SENASICA (I, II, III o ninguno) y Ley General de Salud (estupefaciente art. 234, psicotrópico fracción II, III o IV del art. 245, o ninguna), más la marca antimicrobiano. Hay un catálogo de principios activos precargado que PeluDesk mantiene; lo marcado «por confirmar» hay que confirmarlo con el médico responsable.
- Los productos del Grupo I o de la Ley General de Salud llevan un campo de folio de receta: por ahora solo avisa si falta; más adelante será obligatorio.
- NO existe todavía: consultas, expediente clínico ni recetas (el carnet, los certificados y la hospitalización sí existen: ver más abajo). Si alguien lo pide, se dice que viene en las siguientes fases y se escala; no se promete fecha.
- Nuevos permisos que el admin le da a recepción: Administrar módulos, Editar ficha clínica y Administrar lotes e inventario clínico.

# Veterinaria, Fase 1: carnet, certificados, hospitalización y consentimientos
- Carnet de la mascota (Veterinaria → Carnets): vacunas (biológico, lote, laboratorio, fecha, próxima dosis y el médico veterinario que aplica) y desparasitaciones. El lote y el producto salen del inventario clínico (y descuentan una dosis) o se escriben. Un registro no se edita ni se borra: se anula con motivo y se captura de nuevo. Se imprime y el dueño lo ve en su portal (solo lectura). Registrar es de un médico veterinario, del admin o de quien tenga «Registrar vacunas y desparasitaciones» (apagado por omisión).
- Opción por negocio «El carnet cuenta como comprobante de vacunas» (Veterinaria → Ajustes): una vacuna del carnet ligada a un requisito sanitario (antirrábica, etc.) cubre ese requisito en el check-in de Hotel y Guardería sin subir el documento; apagada por omisión y solo cuenta lo que se registre desde que se prende.
- Carnet verificable: un enlace público con código QR que muestra solo el nombre de la mascota, el del dueño, las vacunas vigentes y el negocio emisor; sin dinero ni datos clínicos. Se genera y se desactiva desde el carnet.
- Recordatorios de próxima dosis: cola en Veterinaria → Recordatorios de dosis, con días de anticipación configurables (7 por omisión) y apagado por mascota. Se mandan a mano con un toque (WhatsApp) o, si el negocio prende el envío automático, salen solos con una plantilla aprobada de WhatsApp, una vez por dosis, de 9:00 a 20:00; ese mensaje sale del número de PeluDesk y dice a qué teléfono del negocio llamar (el número no recibe respuestas). Apagado por omisión.
- Certificado de salud: a nombre de un médico veterinario con cédula, con los datos del establecimiento, la exploración y las vacunas y desparasitaciones vigentes al emitirlo; vigencia configurable (30 días por omisión); se imprime; no se edita, se anula con motivo. Permiso «Emitir certificados» (el médico ya lo tiene).
- Hospitalización (Veterinaria → Hospitalización, funciona con Hotel apagado): ingreso con motivo, médico responsable y ubicación; censo de internados; hoja de medicación con dosis programadas por horario que se marcan como aplicadas (quién y cuándo) y descuentan el lote; monitoreo (temperatura, peso, frecuencias y notas por turno); cargos a la cuenta del dueño (días, medicamentos con precio por dosis, procedimientos) que se cobra en Caja y en cobro junto; depósito inicial opcional, que se aplica a la cuenta al dar el alta; alta con resumen. Permiso «Hospitalizar y medicar» (el médico ya lo tiene).
- Consentimientos informados (hospitalización, cirugía, anestesia, eutanasia): plantillas del negocio editables por versiones con el permiso «Plantillas de contrato»; se firman en pantalla en el mostrador y generan un PDF sellado con hora, IP y hash, como un contrato. Los textos que vienen son una base para que el negocio los revise con su asesor legal.
- Todo esto aparece solo con el módulo Veterinaria prendido. NO existe todavía: consultas, expediente clínico, recetas ni facturación veterinaria.

# Facturación (CFDI 4.0) a los clientes del negocio
- Es distinto de la factura de PeluDesk al negocio: esto es que el negocio le facture a SUS clientes.
- Se configura en Administración → Facturación: RFC, razón social, régimen, código postal de expedición, serie y la llave del PAC (Facturapi). Sin la llave no se timbra. Con una llave de pruebas (sk_test) las facturas salen en sandbox y NO tienen validez fiscal.
- Se factura desde un cobro ya registrado (botón Facturar) o desde un cobro junto (una sola factura). Se factura lo cobrado, sin la propina. Hace falta el permiso «Facturar» y los datos fiscales del cliente (RFC, nombre tal cual su constancia, código postal, régimen y uso del CFDI); se capturan en su ficha con el permiso «Editar datos fiscales».
- IVA por concepto: medicinas veterinarias de patente 0 %; alimento para mascotas, estética, hospedaje y guardería 16 %; consulta veterinaria exenta solo si el negocio es persona física o sociedad civil. Se ajusta en Facturación. Las claves del SAT de arranque son genéricas: el negocio debe poner las suyas.
- Factura global al público en general: junta los cobros que nadie facturó, por periodo (diario, semanal o mensual; en RESICO solo mensual) y debe emitirse dentro de las 24 horas siguientes al cierre del periodo. Puede ser a mano o, si el negocio lo prende, automática.
- Se puede bajar el PDF y el XML, mandar un link por WhatsApp o enviar la factura por correo. Si el cliente tiene portal, la ve en Mis facturas.
- Cancelar o sustituir: con el permiso «Cancelar facturas»; motivos 01 a 04 (el 01 lleva el UUID de la factura que sustituye). Algunas cancelaciones quedan pendientes hasta 3 días a que el cliente las acepte. No se cancela una factura que tiene otra vigente relacionada.
- Un cobro ya facturado no se puede anular, corregir ni devolver mientras su factura esté vigente.
- Cada negocio tiene un tope de timbres al mes; la app avisa al acercarse y PeluDesk puede ampliarlo.
- Lo que NO hace todavía: complemento de pago ni facturar cobros a crédito, notas de crédito (egreso) por devoluciones, ni CFDI de nómina. Si lo piden, se escala.
`.trim();
